---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.1.20
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab-main_ed25519

    k3s_cluster:
      vars:
        ansible_become: true
        ansible_become_pass: "{{ vault_vm_password }}"
      children:
        masters:
          hosts:
            k3s-master-01:
              ansible_host: 192.168.1.25
              ansible_user: cn
              ansible_ssh_private_key_file: ~/.ssh/homelab-main_ed25519
              k3s_role: server
        workers:
          hosts:
            k3s-worker-01:
              ansible_host: 192.168.1.30
              ansible_user: cn
              ansible_ssh_private_key_file: ~/.ssh/homelab-main_ed25519
              k3s_role: agent
            k3s-worker-02:
              ansible_host: 192.168.1.31
              ansible_user: cn
              ansible_ssh_private_key_file: ~/.ssh/homelab-main_ed25519
              k3s_role: agent
